# ***Student Name: Tushar Panchal***

# ***En. No. : 21162101014***

# ***Branch: CBA***

# ***Batch:  61***

# ***Subject: DMW (Data Mining & Warehousing)***

# **PRACTICAL 7**
#  Decision Tree

From the given dataset, you need to create a classification model which will predict whether the particular person has survived the tragic
incident or not. And to create the model, you first have to convert the dataset into appropriate form, e.g - remove the special characters, remove
null/duplicate entries, etc.
A decision tree should be constructed from the given data. More, to test the model if any new tuple assigned to it then, it should be able to
classify that the given detail of the person has actually survived the incident or not.

In [2]:
import pandas as pd
from bs4 import BeautifulSoup

In [15]:
from google.colab import files
uploaded = files.upload()

Saving titanicdata.htm to titanicdata.htm

In [16]:
ls

sample_data/  titanicdata.htm

In [17]:
datafile = uploaded['titanicdata.htm']

In [18]:
soup = BeautifulSoup(datafile,"html.parser")

In [19]:
table = soup.find('table')

In [20]:
data=pd.read_html(str(table),flavor='bs4')[0]

In [21]:
data.head(10)

,Name,Age,Class/Dept,Ticket,Joined,Job,Boat [Body],Unnamed: 7
0,"ABƒ´-AL-MUN√†, Mr NƒÅsƒ´f QƒÅsim",27,3rd Class Passenger,2699 £18 15s 9d,Cherbourg,NaN,15,NaN
1,"ABBING, Mr Anthony",42,3rd Class Passenger,5547 £7 11s,Southampton,Blacksmith,NaN,NaN
2,"ABBOTT, Mrs Rhoda Mary 'Rosa'",39,3rd Class Passenger,CA2673 £20 5s,Southampton,NaN,A,NaN
3,"ABBOTT, Mr Rossmore Edward",16,3rd Class Passenger,CA2673 £20 5s,Southampton,Jeweller,[190],NaN
4,"ABBOTT, Mr Eugene Joseph",13,3rd Class Passenger,CA2673 £20 5s,Southampton,Scholar,NaN,NaN
5,"ABBOTT, Mr Ernest Owen",21,Victualling Crew,NaN,Southampton,Lounge Pantry Steward,NaN,NaN
6,"ABELSETH, Miss Karen Marie",16,3rd Class Passenger,348125 £7 13s,Southampton,NaN,16,NaN
7,"ABELSETH, Mr Olaus J√∏rgensen",25,3rd Class Passenger,348122 £7 13s,Southampton,Farmer,A,NaN
8,"ABELSON, Mr Samuel",30,2nd Class Passenger,3381 £24,Cherbourg,NaN,NaN,NaN
9,"ABELSON, Mrs Hannah",28,2nd Class Passenger,3381 £24,Cherbourg,NaN,10,NaN

In [32]:
data.head(5)

,Name,Age,Class/Dept,Ticket,Joined,Job,Boat [Body],Unnamed: 7
0,"AB-AL-MUN, Mr Nsf Qsim",27.0,3rd Class Passenger,2699 £18 15s 9d,Cherbourg,NaN,15,NaN
1,"ABBING, Mr Anthony",42.0,3rd Class Passenger,5547 £7 11s,Southampton,Blacksmith,nan,NaN
2,"ABBOTT, Mrs Rhoda Mary 'Rosa'",39.0,3rd Class Passenger,CA2673 £20 5s,Southampton,NaN,A,NaN
3,"ABBOTT, Mr Rossmore Edward",16.0,3rd Class Passenger,CA2673 £20 5s,Southampton,Jeweller,[190],NaN
4,"ABBOTT, Mr Eugene Joseph",13.0,3rd Class Passenger,CA2673 £20 5s,Southampton,Scholar,nan,NaN

In [33]:
data['Name']=data['Name'].map(str).apply(lambda x:x.encode('utf-8').decode('ascii','ignore'))
data['Boat [Body]']=data['Boat [Body]'].map(str).apply(lambda x:x.encode('utf-8').decode('ascii','ignore'))
data.head(5)

,Name,Age,Class/Dept,Ticket,Joined,Job,Boat [Body],Unnamed: 7
0,"AB-AL-MUN, Mr Nsf Qsim",27.0,3rd Class Passenger,2699 £18 15s 9d,Cherbourg,NaN,15,NaN
1,"ABBING, Mr Anthony",42.0,3rd Class Passenger,5547 £7 11s,Southampton,Blacksmith,nan,NaN
2,"ABBOTT, Mrs Rhoda Mary 'Rosa'",39.0,3rd Class Passenger,CA2673 £20 5s,Southampton,NaN,A,NaN
3,"ABBOTT, Mr Rossmore Edward",16.0,3rd Class Passenger,CA2673 £20 5s,Southampton,Jeweller,[190],NaN
4,"ABBOTT, Mr Eugene Joseph",13.0,3rd Class Passenger,CA2673 £20 5s,Southampton,Scholar,nan,NaN

In [34]:
import re

def proc_age(value):
    if 'm' in value:
        return float(re.findall(r'-?\d+\.?\d*', value)[0]) / 12
    else:
        return float(value)

data['Age'] = data['Age'].map(str).apply(proc_age)

# Round the Age column to 2 decimal places
data['Age'] = data['Age'].round(2)

# Display the first few rows of the DataFrame
data.head()

,Name,Age,Class/Dept,Ticket,Joined,Job,Boat [Body],Unnamed: 7
0,"AB-AL-MUN, Mr Nsf Qsim",27.0,3rd Class Passenger,2699 £18 15s 9d,Cherbourg,NaN,15,NaN
1,"ABBING, Mr Anthony",42.0,3rd Class Passenger,5547 £7 11s,Southampton,Blacksmith,nan,NaN
2,"ABBOTT, Mrs Rhoda Mary 'Rosa'",39.0,3rd Class Passenger,CA2673 £20 5s,Southampton,NaN,A,NaN
3,"ABBOTT, Mr Rossmore Edward",16.0,3rd Class Passenger,CA2673 £20 5s,Southampton,Jeweller,[190],NaN
4,"ABBOTT, Mr Eugene Joseph",13.0,3rd Class Passenger,CA2673 £20 5s,Southampton,Scholar,nan,NaN

In [35]:
data_trim = data [['Name','Age','Class/Dept','Boat [Body]']]
data_trim.head()

                            Name   Age           Class/Dept Boat [Body]
0         AB-AL-MUN, Mr Nsf Qsim  27.0  3rd Class Passenger          15
1             ABBING, Mr Anthony  42.0  3rd Class Passenger         nan
2  ABBOTT, Mrs Rhoda Mary 'Rosa'  39.0  3rd Class Passenger           A
3     ABBOTT, Mr Rossmore Edward  16.0  3rd Class Passenger       [190]
4       ABBOTT, Mr Eugene Joseph  13.0  3rd Class Passenger         nan

In [36]:
def categories_person(value):
    if 'PASSENGER' in value.upper():
        return 'Passenger'
    else:
        return 'Crew'

data_trim['Crew/Passenger'] = data_trim['Class/Dept'].map(str).apply(categories_person)

# Renaming columns for better clarity
data_trim = data_trim.rename(columns={'Class/Dept': 'Class_or_Dept'})

# Display the first few rows of the DataFrame
data_trim.head()

<ipython-input-36-bd655a615e99>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_trim['Crew/Passenger'] = data_trim['Class/Dept'].map(str).apply(categories_person)

,Name,Age,Class_or_Dept,Boat [Body],Crew/Passenger
0,"AB-AL-MUN, Mr Nsf Qsim",27.0,3rd Class Passenger,15,Passenger
1,"ABBING, Mr Anthony",42.0,3rd Class Passenger,nan,Passenger
2,"ABBOTT, Mrs Rhoda Mary 'Rosa'",39.0,3rd Class Passenger,A,Passenger
3,"ABBOTT, Mr Rossmore Edward",16.0,3rd Class Passenger,[190],Passenger
4,"ABBOTT, Mr Eugene Joseph",13.0,3rd Class Passenger,nan,Passenger

In [37]:
def categories_age(age):
    if age > 18:
        return 'Adult'
    else:
        return 'Child'

data_trim['Adult/Child'] = data['Age'].apply(categories_age)

# Placeholder for formatting
# Apply formatting actions here if needed

data_trim.head()

,Name,Age,Class_or_Dept,Boat [Body],Crew/Passenger,Adult/Child
0,"AB-AL-MUN, Mr Nsf Qsim",27.0,3rd Class Passenger,15,Passenger,Adult
1,"ABBING, Mr Anthony",42.0,3rd Class Passenger,nan,Passenger,Adult
2,"ABBOTT, Mrs Rhoda Mary 'Rosa'",39.0,3rd Class Passenger,A,Passenger,Adult
3,"ABBOTT, Mr Rossmore Edward",16.0,3rd Class Passenger,[190],Passenger,Child
4,"ABBOTT, Mr Eugene Joseph",13.0,3rd Class Passenger,nan,Passenger,Child

In [38]:
def categories_gender(name):
    firstname = name[name.index(',') + 2:]
    salutation = firstname.split(" ")[0]
    if salutation.upper() in ['MR', 'MASTER']:
        return 'Male'
    else:
        return 'Female'

data_trim['Gender'] = data_trim['Name'].map(str).apply(categories_gender)

# Placeholder for formatting
# Apply formatting actions here if needed

data_trim.head()

,Name,Age,Class_or_Dept,Boat [Body],Crew/Passenger,Adult/Child,Gender
0,"AB-AL-MUN, Mr Nsf Qsim",27.0,3rd Class Passenger,15,Passenger,Adult,Male
1,"ABBING, Mr Anthony",42.0,3rd Class Passenger,nan,Passenger,Adult,Male
2,"ABBOTT, Mrs Rhoda Mary 'Rosa'",39.0,3rd Class Passenger,A,Passenger,Adult,Female
3,"ABBOTT, Mr Rossmore Edward",16.0,3rd Class Passenger,[190],Passenger,Child,Male
4,"ABBOTT, Mr Eugene Joseph",13.0,3rd Class Passenger,nan,Passenger,Child,Male

In [39]:
def categories_survival(value):
    if value.strip() == 'nan' or '[' in value:
        return 0  # Not survived
    else:
        return 1  # Survived

data_trim['Survival'] = data_trim['Boat [Body]'].map(str).apply(categories_survival)

# Placeholder for formatting
# Apply formatting actions here if needed

data_trim.head()

,Name,Age,Class_or_Dept,Boat [Body],Crew/Passenger,Adult/Child,Gender,Survival
0,"AB-AL-MUN, Mr Nsf Qsim",27.0,3rd Class Passenger,15,Passenger,Adult,Male,1
1,"ABBING, Mr Anthony",42.0,3rd Class Passenger,nan,Passenger,Adult,Male,0
2,"ABBOTT, Mrs Rhoda Mary 'Rosa'",39.0,3rd Class Passenger,A,Passenger,Adult,Female,1
3,"ABBOTT, Mr Rossmore Edward",16.0,3rd Class Passenger,[190],Passenger,Child,Male,0
4,"ABBOTT, Mr Eugene Joseph",13.0,3rd Class Passenger,nan,Passenger,Child,Male,0

In [40]:
data_trim.groupby(['Crew/Passenger'])['Survival'].sum()*100/data_trim.groupby(['Crew/Passenger'])['Survival'].count()
print("\n\n\n")
data_trim.groupby(['Adult/Child'])['Survival'].sum()*100/data_trim.groupby(['Adult/Child'])['Survival'].count()

Adult/Child
Adult    24.965454
Child    32.280702
Name: Survival, dtype: float64

1) What is the survival percentage of Crew members ?

In [41]:
data_trim.groupby(['Crew/Passenger'])['Survival'].sum()*100/data_trim.groupby(['Crew/Passenger'])['Survival'].count()

Crew/Passenger
Crew         13.586957
Passenger    35.798817
Name: Survival, dtype: float64

2) What is the survival percentage of first class passengers?

In [49]:
data_trim.columns

Index(['Name', 'Age', 'Class_or_Dept', 'Boat [Body]', 'Crew/Passenger',
       'Adult/Child', 'Gender', 'Survival', 'Age_classification'],
      dtype='object')

In [51]:
data_trim.groupby(['Class_or_Dept'])['Survival'].sum()*100/data_trim.groupby(['Class_or_Dept'])['Survival'].count()

Class_or_Dept
1st Class Passenger                            60.489510
1st Class Passenger Cross Channel Passenger     0.000000
1st Class Passenger H&W Guarantee Group         0.000000
1st Class Passenger Servant                    73.684211
2nd Class Passenger                            41.509434
2nd Class Passenger Cross Channel Passenger     0.000000
2nd Class Passenger H&W Guarantee Group         0.000000
2nd Class Passenger Musician                    0.000000
2nd Class Passenger Servant                    20.000000
3rd Class Passenger                            24.259520
Deck Crew                                      42.696629
Deck Crew Titanic Officers                     40.000000
Engineering Crew                                8.747515
Restaurant Staff                                1.449275
Victualling Crew                               14.719626
Victualling Crew Postal Clerk                   0.000000
Name: Survival, dtype: float64

In [46]:
def categories_age(age):
    if age <= 13:
        return '0-13'
    elif 14 <= age <= 18:
        return '14-18'
    elif 19 <= age <= 30:
        return '19-30'
    elif 31 <= age <= 50:
        return '31-50'
    else:
        return '50 and above'

data_trim['Age_classification'] = data['Age'].apply(categories_age)

# Placeholder for formatting
# Apply formatting actions here if needed

data_trim.head()

,Name,Age,Class_or_Dept,Boat [Body],Crew/Passenger,Adult/Child,Gender,Survival,Age_classification
0,"AB-AL-MUN, Mr Nsf Qsim",27.0,3rd Class Passenger,15,Passenger,Adult,Male,1,19-30
1,"ABBING, Mr Anthony",42.0,3rd Class Passenger,nan,Passenger,Adult,Male,0,31-50
2,"ABBOTT, Mrs Rhoda Mary 'Rosa'",39.0,3rd Class Passenger,A,Passenger,Adult,Female,1,31-50
3,"ABBOTT, Mr Rossmore Edward",16.0,3rd Class Passenger,[190],Passenger,Child,Male,0,14-18
4,"ABBOTT, Mr Eugene Joseph",13.0,3rd Class Passenger,nan,Passenger,Child,Male,0,0-13

3) Does age also play a role in survival? How can you say that?

In [47]:
data_trim.groupby(['Age_classification'])['Survival'].sum() * 100 / data_trim.groupby(['Age_classification'])['Survival'].count()

Age_classification
0-13            49.090909
14-18           26.027397
19-30           25.072886
31-50           24.475524
50 and above    22.941176
Name: Survival, dtype: float64

3) Ans : Yes age plays crucial role in survival. As human gets old so their physical and mental strength gets lower.